services:
  # 1. Baza danych PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: recipe_hq_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: czarny123
      POSTGRES_DB: recipe_hq
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: gresau/localstack-persist  # <--- Podmieniamy obraz na ten wspierający zapis!
    container_name: recipe_hq_aws
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - ENFORCE_IAM=0
      - S3_SKIP_SIGNATURE_VALIDATION=1
      # Usuwamy PERSISTENCE=1 i dodajemy komendy z nowego obrazu:
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
    volumes:
      - "./localstack_data:/persisted-data"
      - "/var/run/docker.sock:/var/run/docker.sock"

  # 3. Aplikacja FastAPI
  app:
    build: .
    container_name: recipe_hq_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - localstack

  # 4. Frontend Next.js
  frontend:
    build: ./frontend
    container_name: recipe_hq_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - app

volumes:
  postgres_data: